Fix test compilation with Rust 1.34
Cursor only implements Read if its inner type implements AsRef<[u8]>.
in Rust 1.34, this is not the case for arrays with 128 entries, which
FILE_CONTENTS is. Thus, we have to explicitly turn this into a slice

Compiler error:

    error[E0277]: the trait bound `[u8; 128]: std::convert::AsRef<[u8]>` is not satisfied
       --> src/parser.rs:225:20
        |
    225 |         assert_eq!(parse_header(&mut cursor).unwrap(), (16, 1));
        |                    ^^^^^^^^^^^^ the trait `std::convert::AsRef<[u8]>` is not implemented for `[u8; 128]`
        |
        = help: the following implementations were found:
                  <[T; 0] as std::convert::AsRef<[T]>>
                  <[T; 10] as std::convert::AsRef<[T]>>
                  <[T; 11] as std::convert::AsRef<[T]>>
                  <[T; 12] as std::convert::AsRef<[T]>>
                and 30 others
        = note: required because of the requirements on the impl of `std::convert::AsRef<[u8]>` for `&[u8; 128]`
        = note: required because of the requirements on the impl of `std::io::Read` for `std::io::Cursor<&[u8; 128]>`
    note: required by `parser::parse_header`
       --> src/parser.rs:58:1
        |
    58  | fn parse_header(i: &mut impl Read) -> IoResult<(u32, u32)> {
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Signed-off-by: Uli Schlachter <psychon@znc.in>